/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../Components/AppFooter.vue')['default']
    AppHead: typeof import('./../Components/AppHead.vue')['default']
    InertiaHead: typeof import('@inertiajs/vue3')['Head']
    InertiaLink: typeof import('@inertiajs/vue3')['Link']
  }
}
