/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../Components/AppFooter.vue')['default']
    AppHead: typeof import('./../Components/AppHead.vue')['default']
    ApplicationSlideOver: typeof import('./../Components/Partials/ApplicationSlideOver.vue')['default']
    InertiaHead: typeof import('@inertiajs/vue3')['Head']
    InertiaLink: typeof import('@inertiajs/vue3')['Link']
    InputField: typeof import('./../Components/Inputs/InputField.vue')['default']
    Modal: typeof import('./../Components/Modal.vue')['default']
    ModalConfirm: typeof import('./../Components/ModalConfirm.vue')['default']
    NoteSlideOver: typeof import('./../Components/Partials/NoteSlideOver.vue')['default']
    Pagination: typeof import('./../Components/Pagination.vue')['default']
    SelectField: typeof import('./../Components/Inputs/SelectField.vue')['default']
    SlideOver: typeof import('./../Components/SlideOver.vue')['default']
    StatsPanel: typeof import('./../Components/StatsPanel.vue')['default']
    StatusBadge: typeof import('./../Components/StatusBadge.vue')['default']
    ThemeToggle: typeof import('./../Components/ThemeToggle.vue')['default']
    TipTap: typeof import('./../Components/Inputs/TipTap.vue')['default']
    VueDatePicker: typeof import('@vuepic/vue-datepicker')['VueDatePicker']
  }
}
