/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../Components/AppFooter.vue')['default']
    AppHead: typeof import('./../Components/AppHead.vue')['default']
    InertiaHead: typeof import('@inertiajs/vue3')['Head']
    InertiaLink: typeof import('@inertiajs/vue3')['Link']
    Input: typeof import('./../Components/Inputs/Input.vue')['default']
    InputField: typeof import('./../Components/Inputs/InputField.vue')['default']
    Modal: typeof import('./../Components/Modal.vue')['default']
    ModalConfirm: typeof import('./../Components/ModalConfirm.vue')['default']
    StatsPanel: typeof import('./../Components/StatsPanel.vue')['default']
  }
}
